site_name: Prodigy X
site_url: https://prodigyx.org

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - toc.follow
    - toc.integrate
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - social
  - meta
  - mkdocs-video:
      css_style:
        width: "39.43vw"
        height: "22.172vw"

extra:
  analytics:
    provider: google
    property: G-B3NLTQQJX5

extra_css:
  - stylesheets/global.css

extra_javascript:
  - javascript/copy-button.js

nav:
  - Prodigy X: index.md
  - Installing: installing.md
  - Installing On Mobile: installing-mobile.md
  - Creating Bookmarks: creating-bookmarks.md
  - Contributing:
    - Creating Hacks: contributing/creating-hacks.md
    - Creating Alerts: contributing/alerts.md

repo_url: https://github.com/ProdigyAPI/ProdigyX
repo_name: ProdigyAPI/ProdigyX
